// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmdntrmuhyugpqjbqiwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZG50cm11aHl1Z3BxamJxaXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MjA0MTIsImV4cCI6MjA3ODQ5NjQxMn0.TBDFAeG2Q5zYBjj8_8UoYniTpj03FpR15AejSxrVUzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});